# -*- coding: utf-8 -*-
"""day 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/111LN3jl5kRl0QyXmEwI00OiNzwO1Kz2i
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
study_hours=np.array([1,2,3,4,5,6,7,8,9,10]).reshape(-1,1)
exam_scores = np.array([35,45,50,60,65,70,75,85,88,95])
X_train,X_test,Y_train,Y_test=train_test_split(study_hours,exam_scores,test_size=0.2,random_state=42)
print(f"Total Samples:{len(study_hours)}")
print(f"Training samples: {len(X_train)}")
print(f"Testing samples: {len(X_test)}")
print(f"\nX_train:{X_train.flatten()}")
print(f"Y_train: {Y_train}")

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

study_hours = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(-1,1)
exam_scores = np.array([35,45,50,60,65,70,75,85,88,95])

X_train, X_test, y_train, y_test = train_test_split(
    study_hours, exam_scores,
    test_size=0.2,
    random_state=42
)
model=LinearRegression()
model.fit(X_train,y_train)
print(f"Slope (Coeffient):{model.coef_[0]:.2f}")
print(f"Intercept:{model.intercept_:.2f}")
print(f"Equation Score:{model.coef_[0]:.2f} x Hours + {model.intercept_:.2f}")
y_pred=model.predict(X_test)
print(f"Actual Score:{y_test}")
print(f"Predict Score:{y_pred.round(2)}")
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print(f"\nMSE: {mse:.2f}")
print(f"R² Score: {r2:.2f}")

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

study_hours = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(-1,1)
exam_scores = np.array([35,45,50,60,65,70,75,85,88,95])

X_train, X_test, y_train, y_test = train_test_split(
    study_hours, exam_scores,
    test_size=0.2,
    random_state=42
)
model=LinearRegression()
model.fit(X_train,y_train)
new_students = np.array([3, 5, 7, 10]).reshape(-1,1)
predictions=model.predict(new_students)
print("Study Hours --> Predicted Score:")
for hours, score in zip(new_students.flatten(), predictions):
    print(f"  {hours} hours → {score:.1f} marks")
print("\nGrade Prediction:")
for hours, score in zip(new_students.flatten(), predictions):
    if score >= 80:
        grade = "A"
    elif score >= 65:
        grade = "B"
    elif score >= 50:
        grade = "C"
    else:
        grade = "F"
    print(f"  {hours} hours study → {score:.1f} marks → Grade {grade}")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv("/content/Student_performance_data _.csv")
X = df[["StudyTimeWeekly", "Absences", "Tutoring", "ParentalSupport"]]
y = df["GPA"]

print(f"Features shape: {X.shape}")
print(f"Target shape: {y.shape}")
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(f"\nTraining samples: {len(X_train)}")
print(f"Testing samples: {len(X_test)}")
model = LinearRegression()
model.fit(X_train, y_train)
print("\nFeature Coefficients:")
for feature, coef in zip(X.columns, model.coef_):
    print(f"  {feature}: {coef:.4f}")
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mse)

print(f"\nModel Performance:")
print(f"  R² Score: {r2:.4f}")
print(f"  RMSE: {rmse:.4f}")
print(f"  MSE: {mse:.4f}")
print("\nSample Predictions (first 5):")
print(f"{'Actual GPA':<15} {'Predicted GPA':<15} {'Difference'}")
for actual, pred in list(zip(y_test, y_pred))[:5]:
    diff = abs(actual - pred)
    print(f"{actual:<15.2f} {pred:<15.2f} {diff:.2f}")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df = pd.read_csv("/content/Student_performance_data _.csv")

X = df[["StudyTimeWeekly", "Absences", "Tutoring", "ParentalSupport"]]
y = df["GPA"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)
new_students = pd.DataFrame({
    "StudyTimeWeekly": [15, 5, 10, 18],
    "Absences": [2, 25, 10, 0],
    "Tutoring": [1, 0, 1, 1],
    "ParentalSupport": [4, 0, 2, 3]
})
predict_GPA=model.predict(new_students)
new_students["predicted_gpa"]=predict_GPA
for index,student in new_students.iterrows():
  GPA=student["predicted_gpa"]
  if GPA >=3.5:
    grade="A"
  elif GPA>=2.5:
    grade="B"
  elif GPA>=1.5:
    grade="C"
  else:
    grade="F"

  if student["Absences"]>15 and GPA<1.5:
    risk="AI RISK!"
  else:
    risk="OK"
  if student["Tutoring"]==1:
    tutoring_status = "Yes"
  else:
    tutoring_status = "No"

  print(f"Student {index+1}:Study ={student['StudyTimeWeekly']},Absence={student['Absences']},Turtoring={tutoring_status} ->GPA:{GPA:.2f} -> Grade{grade} ->{risk}")