# -*- coding: utf-8 -*-
"""day 6 ai&ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mcRwoqvoaUkNgql2ENrt73xU8PIcFzk7
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/Student_performance_data _.csv")
print("="*50)
print("PROJECT: Student Performance Analyzer")
print("="*50)
print(f"Total students: {df.shape[0]}")
print(f"Total features: {df.shape[1]}")
print(f"\nMissing values: {df.isnull().sum().sum()}")
print(f"Duplicate rows: {df.duplicated().sum()}")

import pandas as pd
import numpy as np
df = pd.read_csv("/content/Student_performance_data _.csv")
print("="*50)
print("EXPLORATORY DATA ANALYSIS")
print("="*50)
print("\n1. GPA Statistics:")
print(f"   Mean GPA: {df['GPA'].mean():.2f}")
print(f"   Median GPA: {df['GPA'].median():.2f}")
print(f"   Std Dev: {df['GPA'].std():.2f}")

print("\n2. Study Time Statistics:")
print(f"   Mean: {df['StudyTimeWeekly'].mean():.2f} hrs/week")
print(f"   Max: {df['StudyTimeWeekly'].max():.2f} hrs/week")
print(f"   Min: {df['StudyTimeWeekly'].min():.2f} hrs/week")

print("\n3. Absences Statistics:")
print(f"   Mean: {df['Absences'].mean():.2f} days")
print(f"   Max: {df['Absences'].max()} days")

print("\n4. Grade Distribution:")
grade_map = {0: "A", 1: "B", 2: "C", 3: "D", 4: "F"}
df["GradeLabel"] = df["GradeClass"].map(grade_map)
print(df["GradeLabel"].value_counts())

print("\n5. Correlation with GPA:")
correlations = df[["StudyTimeWeekly", "Absences", "Age", "GPA"]].corr()["GPA"]
print(correlations.round(3))

print("="*50)
print("EXPLORATORY DATA ANALYSIS")
print("="*50)
print("\n1. GPA Statistics:")
print(f"   Mean GPA: {df['GPA'].mean():.2f}")
print(f"   Median GPA: {df['GPA'].median():.2f}")
print(f"   Std Dev: {df['GPA'].std():.2f}")

print("\n2. Study Time Statistics:")
print(f"   Mean: {df['StudyTimeWeekly'].mean():.2f} hrs/week")
print(f"   Max: {df['StudyTimeWeekly'].max():.2f} hrs/week")
print(f"   Min: {df['StudyTimeWeekly'].min():.2f} hrs/week")

print("\n3. Absences Statistics:")
print(f"   Mean: {df['Absences'].mean():.2f} days")
print(f"   Max: {df['Absences'].max()} days")

print("\n4. Grade Distribution:")
grade_map = {0: "A", 1: "B", 2: "C", 3: "D", 4: "F"}
df["GradeLabel"] = df["GradeClass"].map(grade_map)
print(df["GradeLabel"].value_counts())

print("\n5. Correlation with GPA:")
correlations = df[["StudyTimeWeekly", "Absences", "Age", "GPA"]].corr()["GPA"]
print(correlations.round(3))

import pandas as pd
import numpy as np

df = pd.read_csv("/content/Student_performance_data _.csv")
grade_map = {0: "A", 1: "B", 2: "C", 3: "D", 4: "F"}
df["GradeLabel"] = df["GradeClass"].map(grade_map)

print("="*50)
print("DEEP INSIGHTS")
print("="*50)

print("\n1. Does Tutoring Help?")
tutoring_gpa = df.groupby("Tutoring")["GPA"].mean()
print(tutoring_gpa.round(3))
diff = tutoring_gpa[1] - tutoring_gpa[0]
print(f"   GPA difference: {diff:.3f}")

print("\n2. Extracurricular Activities Impact:")
extra_gpa = df.groupby("Extracurricular")["GPA"].mean()
print(extra_gpa.round(3))

print("\n3. Parental Support Impact:")
support_map = {0: "None", 1: "Low", 2: "Moderate", 3: "High", 4: "VeryHigh"}
df["SupportLabel"] = df["ParentalSupport"].map(support_map)
print(df.groupby("SupportLabel")["GPA"].mean().sort_values(ascending=False).round(3))

at_risk = df[(df["GPA"] < 1.5) & (df["Absences"] > 15)]
print(f"\n4. At-risk students (GPA<1.5 AND Absences>15): {len(at_risk)}")
print(f"   Percentage: {len(at_risk)/len(df)*100:.2f}%")

top_performers = df[df["GPA"] >= 3.5]
print(f"\n5. High Performers (GPA>=3.5): {len(top_performers)}")
print(f"   Avg study time: {top_performers['StudyTimeWeekly'].mean():.2f} hrs")
print(f"   Avg absences: {top_performers['Absences'].mean():.2f} days")
print(f"   Tutoring %: {top_performers['Tutoring'].mean()*100:.1f}%")

readme_content = """# Student Performance Analyzer

## Project Overview
Analysis of 2392 students' academic performance data to identify
factors affecting GPA — study time, absences, tutoring, and parental
support.

## Objectives
- Explore correlation between study habits and academic performance
- Identify at-risk students based on attendance patterns
- Measure effectiveness of tutoring and parental support

## Tools Used
- Python
- Pandas (data manipulation)
- NumPy (numerical analysis)

## Key Insights
1. Absences show very strong negative correlation with GPA (-0.919)
2. Students with tutoring score 0.289 higher GPA on average
3. 34.36% of students are at-risk (GPA < 1.5 AND Absences > 15)
4. High performers study 12.89 hrs/week with 1.6 days absence
5. Parental support: VeryHigh (2.19) vs None (1.54) — 0.65 difference

## Dataset
2392 student records with 15 features including demographics,
study habits, and academic outcomes.

## Author
Kaviya V | github.com/kaviyavijayan11
"""

with open("README.md", "w") as f:
    f.write(readme_content)

print("README.md created successfully!")