# -*- coding: utf-8 -*-
"""day 9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y_EYlXg9mhHJiaHPWZGMJ0uZqKPcdW92
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
study_hours=np.array([1,2,3,4,5,6,7,8,9,10]).reshape(-1,1)
result=np.array([0,0,0,0,1,1,1,1,1,1])
x_train,x_test,y_train,y_test=train_test_split(
    study_hours,result,test_size=0.2,random_state=42
)
model=LogisticRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_prob=model.predict_proba(x_test)

print(f"Test Samples:{x_test.flatten()}")
print(f"Actual :{y_test}")
print(f"Predict :{y_pred}")
print(f"Probabilities (Fail,Pass) :{y_prob.round(2)}")
print(f"Accuracy :{accuracy_score(y_test,y_pred)*100:.2f}%")

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

np.random.seed(42)
Study=np.random.randint(1,11,100).reshape(-1,1)
Results=(Study.flatten()>=6) .astype(int)
Results[::10]=1-Results[::10]

x_train,x_test,y_train,y_test=train_test_split(
    Study,Results,test_size=0.2,random_state=42)

model=LogisticRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

cm=confusion_matrix(y_test,y_pred)
print(cm)
print(f"\n True Negative(TN):{cm[0][0]}")
print(f"True Postive(TP):{cm[0][1]}")
print(f"False Negative(FN):{cm[1][0]}")
print(f"False Postive(FP):{cm[1][1]}")
print("\nClassification Report")
print(classification_report(y_test,y_pred,target_names=["Fail","Pass"]))

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

df = pd.read_csv("/content/Student_performance_data _.csv")
df["IsGradeA"] = (df["GradeClass"] == 0).astype(int)

print(f"Grade A students: {df['IsGradeA'].sum()}")
print(f"Not Grade A: {(df['IsGradeA']==0).sum()}")
X = df[["StudyTimeWeekly", "Absences",
        "Tutoring", "ParentalSupport"]]
y = df["IsGradeA"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(f"\nAccuracy: {accuracy_score(y_test, y_pred)*100:.2f}%")

cm = confusion_matrix(y_test, y_pred)
print(f"\nConfusion Matrix:")
print(cm)
print(f"\nTrue Grade A correctly identified: {cm[1][1]}")
print(f"Grade A missed: {cm[1][0]}")
print(f"False Grade A alerts: {cm[0][1]}")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv("/content/Student_performance_data _.csv")
X = df[["StudyTimeWeekly", "Absences",
        "Tutoring", "ParentalSupport"]]
y = df["GradeClass"].astype(int)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model = LogisticRegression(max_iter=1000,
                           multi_class="multinomial")
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, y_pred)*100:.2f}%")

grade_map = {0:"A", 1:"B", 2:"C", 3:"D", 4:"F"}
print("\nClassification Report:")
print(classification_report(y_test, y_pred,
      target_names=["A","B","C","D","F"]))
print("\nSample Predictions (first 10):")
print(f"{'Actual':<10} {'Predicted':<10} {'Correct?'}")
for actual, pred in list(zip(y_test, y_pred))[:10]:
    correct = "✅" if actual == pred else "❌"
    grade_a = grade_map[actual]
    grade_p = grade_map[pred]
    print(f"{grade_a:<10} {grade_p:<10} {correct}")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
df = pd.read_csv("/content/Student_performance_data _.csv")

X = df[["StudyTimeWeekly", "Absences",
        "Tutoring", "ParentalSupport"]]

y = df["GradeClass"].astype(int)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression(
    max_iter=1000,
    multi_class="multinomial"
)

model.fit(X_train, y_train)

new_students = pd.DataFrame({
    "StudyTimeWeekly": [18, 3, 10, 15],
    "Absences": [0, 28, 12, 5],
    "Tutoring": [1, 0, 1, 0],
    "ParentalSupport": [4, 0, 2, 3]
})
grade_map = {
    0: "A",
    1: "B",
    2: "C",
    3: "D",
    4: "F"
}


predictions = model.predict(new_students)
probabilities = model.predict_proba(new_students)
for i in range(len(new_students)):

    student = new_students.iloc[i]
    pred = predictions[i]
    grade = grade_map[pred]
    confidence = probabilities[i][pred] * 100
    tutoring = "Yes" if student["Tutoring"] == 1 else "No"
    if grade == "F":
        advice = "Needs immediate attention!"
    elif grade == "D":
        advice = "Needs improvement"
    elif grade == "C":
        advice = "Average — can do better"
    else:
        advice = "Keep it up!"
    print(
        f"Student {i+1}: "
        f"Study={student['StudyTimeWeekly']}, "
        f"Absence={student['Absences']}, "
        f"Tutoring={tutoring} "
        f"→ Grade: {grade}, "
        f"Confidence: {confidence:.2f}% "
        f"→ {advice}"
    )