# -*- coding: utf-8 -*-
"""day 1 ai&ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12QErEV96b5BtDMdVnGwtYrD0DHWG233j
"""

def even(number):
  even=[]
  for n in number:
    if n%2 ==0:
      even.append(n)
  return even
number=[2,3,4,5,6]
print(even(number))

students={
    "Ravi":91,
    "Kaviya":85,
    "Raja":62,
    "Rani":45,
}
pass_list=[]
fail_list=[]
for name,marks in students.items():
  if marks>=75:
    pass_list.append(name)
  else:
    fail_list.append(name)
print("passed:",pass_list)
print("Failed:",fail_list)

def delivery_charge(distance):
  if distance<5:
    return "Free Delivery"
  elif distance<10:
    return "Delivery charge:30"
  else:
    return "Delivery charge:60"
print(delivery_charge(4))
print(delivery_charge(8))
print(delivery_charge(15))

scores = [45, 72, 31, 88, 55, 91, 23, 67]
total=sum(scores)
count=len(scores)
average=total/count
Highest=max(scores)
Lowest=min(scores)
above_avg=[]
for score in scores:
  if score>average:
    above_avg.append(score)
print(f"Total runs: {total}")
print(f"Players: {count}")
print(f"Average: {average}")
print(f"Highest: {Highest}")
print(f"Lowest: {Lowest}")
print(f"Above average scores: {above_avg}")

products = {
    "Shirt": 450,
    "Jeans": 1200,
    "Shoes": 800,
    "Watch": 2500,
    "Cap": 299,
    "Belt": 650
}

def categorize_product(price):

   if price <500:
      return "Affordable"
   elif price <1000:
      return  "Medium"
   else:
      return "Expensive"


for product, price in products.items():
    category = categorize_product(price)
    print(f"{product} (Rs.{price}) → {category}")