# -*- coding: utf-8 -*-
"""day 10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TYglVwWaCPG5MsyfZHQ4MaXEX9kASfgE
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv("/content/Student_performance_data _.csv")

X = df[["StudyTimeWeekly", "Absences",
        "Tutoring", "ParentalSupport"]]
y = df["GradeClass"].astype(int)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
y_pred = dt_model.predict(X_test)

print("Decision Tree Results:")
print(f"Accuracy: {accuracy_score(y_test, y_pred)*100:.2f}%")
print(f"Tree Depth: {dt_model.get_depth()}")
print(f"Total Leaves: {dt_model.get_n_leaves()}")
print(f"\nFeature Importances:")
for feature, importance in zip(X.columns, dt_model.feature_importances_):
    print(f"  {feature}: {importance:.4f}")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

df = pd.read_csv("/content/Student_performance_data _.csv")

X = df[["StudyTimeWeekly", "Absences",
        "Tutoring", "ParentalSupport"]]
y = df["GradeClass"].astype(int)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Depth | Train Accuracy | Test Accuracy | Status")
print("-"*60)

for depth in [1, 2, 3, 5, 7, 10, None]:
    dt = DecisionTreeClassifier(max_depth=depth,random_state=42)
    dt.fit(X_train, y_train)

    train_acc = accuracy_score(y_train, dt.predict(X_train))*100
    test_acc = accuracy_score(y_test, dt.predict(X_test))*100

    if train_acc - test_acc > 10:
        status = "⚠️ Overfitting"
    elif test_acc < 70:
        status = "❌ Underfitting"
    else:
        status = "✅ Good fit"

    depth_str = str(depth) if depth else "None"
    print(f"{depth_str:<6}| {train_acc:<15.2f}| {test_acc:<14.2f}| {status}")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

df = pd.read_csv("/content/Student_performance_data _.csv")

X = df[["StudyTimeWeekly", "Absences",
        "Tutoring", "ParentalSupport"]]
y = df["GradeClass"].astype(int)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)
dt_acc = accuracy_score(y_test, dt.predict(X_test))*100

rf = RandomForestClassifier(n_estimators=100,random_state=42)
rf.fit(X_train, y_train)
rf_acc = accuracy_score(y_test, rf.predict(X_test))*100

print("Model Comparison:")
print(f"Decision Tree Accuracy : {dt_acc:.2f}%")
print(f"Random Forest Accuracy : {rf_acc:.2f}%")
print(f"Improvement            : +{rf_acc-dt_acc:.2f}%")

print("\nRandom Forest Feature Importances:")
for feature, importance in zip(X.columns,
                                rf.feature_importances_):
    bar = "█" * int(importance * 50)
    print(f"  {feature:<20}: {importance:.4f} {bar}")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

df = pd.read_csv("/content/Student_performance_data _.csv")

X = df[["StudyTimeWeekly", "Absences",
        "Tutoring", "ParentalSupport"]]
y = df["GradeClass"].astype(int)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Tuning Random Forest...")
print(f"{'Trees':<8}{'Max Depth':<12}{'Test Acc':<12}{'Train Acc'}")
print("-"*45)

best_acc = 0
best_params = {}

for n_trees in [10, 50, 100, 200]:
    for max_depth in [3, 5, 10, None]:
        rf = RandomForestClassifier(n_estimators=n_trees,max_depth=max_depth,random_state=42)
        rf.fit(X_train, y_train)
        test_acc = accuracy_score(
            y_test, rf.predict(X_test))*100
        train_acc = accuracy_score(
            y_train, rf.predict(X_train))*100

        if test_acc > best_acc:
            best_acc = test_acc
            best_params = {
                "n_estimators": n_trees,
                "max_depth": max_depth
            }

        depth_str = str(max_depth) if max_depth else "None"
        print(f"{n_trees:<8}{depth_str:<12}"
              f"{test_acc:<12.2f}{train_acc:.2f}")

print(f"\n🏆 Best Accuracy: {best_acc:.2f}%")
print(f"Best Parameters: {best_params}")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

df = pd.read_csv("/content/Student_performance_data _.csv")

X = df[["StudyTimeWeekly", "Absences",
        "Tutoring", "ParentalSupport"]]
y = df["GradeClass"].astype(int)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
lr_acc = accuracy_score(y_test, lr.predict(X_test)) * 100

dt = DecisionTreeClassifier(max_depth=5,random_state=42)
dt.fit(X_train, y_train)
dt_acc = accuracy_score(y_test, dt.predict(X_test)) * 100

rf = RandomForestClassifier(n_estimators=100,random_state=42)
rf.fit(X_train, y_train)
rf_acc = accuracy_score(y_test, rf.predict(X_test)) * 100

models = {
    "Logistic Regression": (lr, lr_acc),
    "Decision Tree": (dt, dt_acc),
    "Random Forest": (rf, rf_acc)
}

best_name = max(models, key=lambda x: models[x][1])
best_model, best_acc = models[best_name]

print("Model Comparison:")
print("=" * 40)

for name, (model, acc) in models.items():
    if name == best_name:
        print(f"{name:<20}: {acc:.2f}%  ← Best!")
    else:
        print(f"{name:<20}: {acc:.2f}%")

print("=" * 40)
print(f"Best Model: {best_name}")

new_student = pd.DataFrame({
    "StudyTimeWeekly": [12],
    "Absences": [8],
    "Tutoring": [1],
    "ParentalSupport": [3]
})

prediction = best_model.predict(new_student)[0]
confidence = best_model.predict_proba(new_student).max() * 100

grade_map = {
    0: "A",
    1: "B",
    2: "C",
    3: "D",
    4: "F"
}

support_map = {
    0: "None",
    1: "Low",
    2: "Medium",
    3: "High",
    4: "Very High"
}

tutoring = "Yes" if new_student["Tutoring"][0] == 1 else "No"

print("\nNew Student Prediction (Best Model):")
print(
    f"Study={new_student['StudyTimeWeekly'][0]}, "
    f"Absence={new_student['Absences'][0]}, "
    f"Tutoring={tutoring}, "
    f"Support={support_map[new_student['ParentalSupport'][0]]}"
)
print(f"→ Predicted Grade: {grade_map[prediction]}")
print(f"→ Confidence: {confidence:.2f}%")