# -*- coding: utf-8 -*-
"""day 3 ai&ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KXt22eOPcJN32Bm3cQfxTnhgij6Fbwz_
"""

marks = [45, 82, 31, 76, 55, 91, 48, 63, 88, 72]
old_method=[]
for m in marks:
  if m >=60:
    old_method.append(m)


new_method=[m for m in marks if m >=60]

doubled=[m*2 for m in marks if m >=60]

grades=["pass" if m >=60 else "fail" for m in marks]

print(f"passed(old) : {old_method}")
print(f"passed(new) : {new_method}")
print(f"doubled : {doubled}")
print(f"grades : {grades}")

def analyze(marks):
  total=len(marks)
  passed=[m for m in marks if m >=60]
  failed=[m for m in marks if m < 60]
  average=sum(marks)/total
  highest=max(marks)
  lowest=min(marks)

  return total,len(passed),len(failed),round(average,2),highest,lowest

marks = [45, 82, 31, 76, 55, 91, 48, 63, 88, 72]

total,passed,fail,avg,high,low=analyze(marks)

print(f"Total Students:{total}")
print(f"passed count:{passed}")
print(f"failed count:{fail}")
print(f"avg:{avg}")
print(f"highest mark:{high}")
print(f"lowest mark:{low}")

class students:
  def __init__(self,name,mark):
    self.name=name
    self.mark=mark

  def get_grade(self):
    if self.mark>=90:
      return "A+"
    elif self.mark>=75:
      return "A"
    elif self.mark>=65:
      return "B"
    else:
      return "F"

  def display(self):
    grade=self.get_grade()
    print (f"{self.name}| Marks:{self.mark}|Grade:{grade}")

s1 = students("Ravi", 85)
s2 = students("Priya", 92)
s3 = students("Karthik", 45)

s1.display()
s2.display()
s3.display()

class BankAccount:
  def __init__(self,owner,balance=0):
    self.owner=owner
    self.balance=balance
    self.transaction=[]
  def deposit(self,amount):
    if amount<=0:
      return "Amount is invalid"
    self.balance+=amount
    self.transaction.append(f"Deposited :+{amount}")
    return f"Deposited Rs.{amount}"

  def withdraw(self,amount):
    if amount>=self.balance:
      return "Insuffient balance"
    if amount<=0:
      return "Amount is invalid"
    self.balance-=amount
    self.transaction.append(f"Withdraw :-{amount}")
    return f"Withdrawn Rs.{amount}"

  def show_balance(self):
    print(f"\n{self.owner}'s account")
    print(f"balance:Rs.{self.balance}")
    print("Transaction")
    for t in self.transaction:
      print(f" {t}")

acc=BankAccount("Ravi",1000)
print(acc.deposit(500))
print(acc.withdraw(200))
print(acc.withdraw(2000))
print(acc.deposit(-100))
acc.show_balance()

class Product:
    def __init__(self, name, price, quantity):
        self.name=name
        self.price=price
        self.quantity=quantity

    def total_cost(self):
        return self.price * self.quantity

    def apply_discount(self, percent):
        discount=(self.price * percent) / 100
        self.price=self.price-discount
        return self.price
    def display(self):
        print(f"{self.name} | Price: {self.price} | Qty: {self.quantity} | Total: {self.total_cost()}")

p1 = Product("Laptop", 50000, 2)
p2 = Product("Phone", 15000, 3)

p1.display()
p1.apply_discount(10)
p1.display()

p2.display()
p2.apply_discount(20)
p2.display()

