# -*- coding: utf-8 -*-
"""day 19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RqBf5C70QP1zqxDxuVKBjZEbK235ovG_
"""

import numpy as np
import pandas as pd
import re
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional
from sklearn.model_selection import train_test_split

print("SENTIMENT CLASSIFIER - MINI PROJECT 3")
reviews = [
    "amazing product love it so much",
    "terrible quality waste of money",
    "excellent product very useful and reliable",
    "worst purchase ever complete disappointment",
    "really happy with this product great value",
    "complete garbage dont waste your money",
    "fantastic quality highly recommend to everyone",
    "very disappointed with this terrible product",
    "wonderful experience loved every part of it",
    "poor quality never buying this again",
    "outstanding performance exceeded my expectations",
    "horrible experience total waste of time",
    "best decision ever so satisfied with purchase",
    "awful product broke within two days",
    "great value for money highly satisfied",
    "disgusting quality avoid this product completely",
    "impressive design and excellent build quality",
    "regret buying this poor customer service",
    "superb quality and fast delivery amazing",
    "useless product money down the drain",
    "loved it works perfectly as described",
    "bad experience product stopped working quickly",
    "highly recommend perfect for daily use",
    "waste of money terrible customer support",
    "exceptional quality worth every penny spent",
    "disappointed quality not as advertised",
    "brilliant product exceeded all expectations",
    "poor packaging product arrived damaged",
    "excellent purchase very happy with quality",
    "not worth the price cheap material used"
]

labels = [1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0]
print(f"Total reviews: {len(reviews)}")
print(f"Positive: {sum(labels)}")
print(f"Negative: {len(labels)-sum(labels)}")
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    return text
cleaned_reviews = [clean_text(r) for r in reviews]
X_train_text, X_test_text, y_train, y_test = train_test_split(cleaned_reviews, labels, test_size=0.2, random_state=42)
print(f"\nTraining samples: {len(X_train_text)}")
print(f"Testing samples: {len(X_test_text)}")

print("\nTOKENIZATION + MODEL BUILDING")
tokenizer = Tokenizer(num_words=200, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train_text)
vocab_size = len(tokenizer.word_index) + 1
print(f"Vocabulary size: {vocab_size}")
X_train_seq = tokenizer.texts_to_sequences(X_train_text)
X_test_seq = tokenizer.texts_to_sequences(X_test_text)
max_length = 8
X_train_pad = pad_sequences(X_train_seq, maxlen=max_length, padding='post')
X_test_pad = pad_sequences(X_test_seq, maxlen=max_length, padding='post')
y_train = np.array(y_train)
y_test = np.array(y_test)
print(f"Training shape: {X_train_pad.shape}")
print(f"Testing shape: {X_test_pad.shape}")
model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=32, input_length=max_length),
    Bidirectional(LSTM(32, return_sequences=True)),
    Bidirectional(LSTM(16)),
    Dense(24, activation='relu'),
    Dropout(0.4),
    Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
print("\nModel Architecture:")
model.summary()

print("\nTRAINING MODEL")
history = model.fit(X_train_pad, y_train,epochs=30,batch_size=4,validation_data=(X_test_pad, y_test),verbose=0)
print("Training completed!")
train_loss, train_acc = model.evaluate(X_train_pad, y_train, verbose=0)
test_loss, test_acc = model.evaluate(X_test_pad, y_test, verbose=0)
print(f"\nTraining Accuracy: {train_acc*100:.2f}%")
print(f"Testing Accuracy: {test_acc*100:.2f}%")
diff = abs(train_acc - test_acc) * 100
print(f"Train-Test Gap: {diff:.2f}%")
if diff > 20:
    print("Status: Overfitting detected")
else:
    print("Status: Reasonable generalization")
predictions = model.predict(X_test_pad, verbose=0)
predicted_labels = (predictions > 0.5).astype(int).flatten()
print("\nTest Set Predictions:")
print(f"{'Review':<50} {'Actual':<10} {'Predicted':<12} {'Correct'}")
print("-"*85)
for i in range(len(X_test_text)):
    actual = "Positive" if y_test[i]==1 else "Negative"
    pred = "Positive" if predicted_labels[i]==1 else "Negative"
    correct = "Yes" if y_test[i]==predicted_labels[i] else "No"
    review_short = X_test_text[i][:45]
    print(f"{review_short:<50} {actual:<10} {pred:<12} {correct}")
print("\nDEBUGGING - CONFIDENCE DISTRIBUTION")
test_words = ["amazing", "terrible", "best", "worst", "good", "bad"]

for word in test_words:
    seq = tokenizer.texts_to_sequences([word])
    if seq[0]:
        print(f"'{word}' -> token: {seq[0]}")
    else:
        print(f"'{word}' -> NOT IN VOCABULARY (OOV)")
print("\nWHAT WOULD FIX THIS:")
print("1. More training data (100s-1000s of reviews)")
print("2. Early stopping (stop before 100% train accuracy)")
print("3. Simpler model (fewer LSTM units)")
print("4. Stronger dropout (0.5+)")
print("5. L2 regularization on LSTM layers")

def predict_sentiment(text):
    cleaned = clean_text(text)
    sequence = tokenizer.texts_to_sequences([cleaned])
    padded = pad_sequences(sequence, maxlen=max_length, padding='post')
    probability = model.predict(padded, verbose=0)[0][0]
    if probability >= 0.5:
        sentiment = "Positive"
        confidence = probability * 100
    else:
        sentiment = "Negative"
        confidence = (1-probability) * 100
    return sentiment, confidence
print("REAL-WORLD TESTING")
new_reviews = [
    "This is the best product I have ever bought",
    "Absolutely terrible dont waste your money",
    "Good quality but delivery was slow",
    "Amazing experience will buy again",
    "Not satisfied with the product quality"
]

print("\nPredictions on completely new reviews:")
for review in new_reviews:
    sentiment, confidence = predict_sentiment(review)
    print(f"\nReview: {review}")
    print(f"Sentiment: {sentiment} (Confidence: {confidence:.1f}%)")
readme_content = f"""# Sentiment Analysis - Product Reviews

## Project Overview
A Bidirectional LSTM neural network that classifies product
reviews as positive or negative sentiment.

## Dataset
- 30 product reviews (balanced: 15 positive, 15 negative)
- Train/test split: 80/20 with proper data leakage prevention

## Model Architecture
- Embedding layer (32 dimensions)
- Bidirectional LSTM (32 units) with return_sequences
- Bidirectional LSTM (16 units)
- Dense layer with Dropout regularization
- Sigmoid output for binary classification

## Results
- Training Accuracy: {train_acc*100:.2f}%
- Testing Accuracy: {test_acc*100:.2f}%
- Train-Test Gap: {diff:.2f}%

## Key Learnings
1. Data leakage prevention - tokenizer fit only on training data
2. Bidirectional LSTM captures context from both directions
3. Small datasets limit generalization (30 samples is minimal)
4. Proper train/test evaluation reveals true model performance

## Limitations
- Small dataset size limits real-world accuracy
- Production systems need thousands of labeled examples
- Model may struggle with sarcasm, complex negation

- Model achieved 100% training accuracy but
failed to generalize on completely new sentences,
demonstrating overfitting despite reasonable
test accuracy (83%).
- Root cause: insufficient
training data (24 samples) for LSTM model
complexity. This highlights the importance of
train-test gap monitoring beyond single metrics."

## Tools Used
- Python, TensorFlow/Keras
- LSTM, Bidirectional layers
- Tokenizer, text preprocessing

## Author
Kaviya V | github.com/kaviyavijayan11
"""

with open("README.md", "w") as f:
    f.write(readme_content)

print("\n\nREADME.md created!")