# -*- coding: utf-8 -*-
"""day 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14s2GFNUba6tcaKCM_axrhgAb0Elaqy8O
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/Student_performance_data _.csv")

print(f"Shape:{df.shape}")
print(f"\nColumns:{df.columns.tolist()}")
print(f"\nFirst 5 Rows:{df.head()} ")
print(f"\nData Types:{df.dtypes}")
print(f"\nBasic States:{df.describe()}")

print(df["GPA"])

high_GPA=df[df["GPA"]>=3.5]
print(f"High GPA students(3.5+):{len(high_GPA)}")
high_GPA_low_absence=df[(df["GPA"]>=3.5)&(df["Absences"]<=5)]
print(f"High GPA + Low Absences:{len(high_GPA_low_absence)}")
grade_a_students=df[df["GradeClass"]==0]
print(f"Grade A Students:{len(grade_a_students)}")
study_GPA=df[["StudyTimeWeekly","Absences","GPA","GradeClass"]]
print("\nStudy VS GPA")
print(study_GPA.head())

import pandas as pd
import numpy as np

df=pd.read_csv("/content/Student_performance_data _.csv")

print("Missing values in the dataset")
print(df.isnull().sum())
print(f"Total missing values in the dataset:{df.isnull().sum().sum()}")

messy=pd.DataFrame({
    "StudentID": [1, 2, 3, 4, 5],
    "GPA": [3.5, None, 2.8, None, 3.9],
    "Absences": [5, 10, None, 8, 3],
    "StudyTime": [15.0, 12.0, None, 18.0, None]
                    }

)

print("\nBefore cleaning")
print(messy)

messy["GPA"]=messy["GPA"].fillna(messy["GPA"].mean())
messy["Absences"]=messy["Absences"].fillna(messy["Absences"].median())
messy["StudyTime"]=messy["StudyTime"].fillna(messy["StudyTime"].mean())
print("\nAfter cleaning:")
print(messy.round(2))

print("Genderwise average GPA:")
print(df.groupby("Gender")["GPA"].mean().round(3))
print("(0 is female and 1 is male)\n")
print("Tutoring impact on GPA")
print(df.groupby("Tutoring")["GPA"].mean().round(3))
print("(0 is no tutoring and 1 is tutoring)\n")
print("Parental support impact on GPA")
print(df.groupby("ParentalSupport")["GPA"].mean().round(3))
print("(0 is none and 4 is very high)\n")
print("Average Study time per grade")
print(df.groupby("GradeClass")["StudyTimeWeekly"].mean().round(3))
print("(0 is A,1 is B,2 is C,3 is D,4 is E and 5 is F)\n")
print("Absences per garde")
print(df.groupby("GradeClass")["Absences"].mean().round(3))

import pandas as pd
import numpy as np

df=pd.read_csv("/content/Student_performance_data _.csv")

print("GPA Distribution")
print(f'Excellent(3.5+):{len(df[df["GPA"]>=3.5])}')
print(f'Good(2.5-3.49):{len(df[(df["GPA"]<=3.49)&(df["GPA"]>=2.5)])}')
print(f'Average(1.5-2.49):{len(df[(df["GPA"]<=2.49)&(df["GPA"]>=1.5)])}')
print(f'Poor(below 1.5):{len(df[df["GPA"]<=1.5])}')

print("\nAbsences Impact")
df["AbsenceGroup"] = pd.cut(df["Absences"],
   bins=[0, 5, 15, 100],
   labels=["Low", "Medium", "High"])
print(df.groupby("AbsenceGroup")["GPA"].mean())

print("\nStudy Category")
conditions=[
    df["StudyTimeWeekly"] >=15,
    (df["StudyTimeWeekly"]>10)&(df["StudyTimeWeekly"]<15),
    df["StudyTimeWeekly"]<10
]
choices=["High","Good","Average"]
df["StudyCategory"]=np.select(conditions,choices,default="Unknown")
print(df.groupby("StudyCategory")["GPA"].mean())

print("\nTop 10 Students:")
print(df.nlargest(10,"GPA")[["StudentID","Age","GPA","GradeClass"]])
