# -*- coding: utf-8 -*-
"""day 2 ai&ml .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NV3EwdDXzqIq4ANLVCwVKcRzsxVg7lYE
"""

name = "  ravi kumar  "
email = "RAVI@GMAIL.COM"
review = "This product is amazing and very useful"
clean_name=name.strip()
proper_name=clean_name.title()
clean_email=email.lower()

word_count=len(review.split())
contains_amazing="amazing" in review
first_word=review.split() [0]

print(f"Name: {proper_name}")
print(f"Email: {clean_email}")
print(f"Word count: {word_count}")
print(f"Contains 'amazing': {contains_amazing}")
print(f"First word: {first_word}")

temperatures = [35, 28, 42, 28, 31, 42, 39, 28, 45, 31]
unique_temp =(list(set(temperatures)))
sorted_temp=(sorted(temperatures))
count_28=temperatures.count(28)
temperatures.append(50)
temperatures.remove(28)

print(f"Original:{temperatures}")
print(f"Unique:{unique_temp}")
print(f"Sorted:{sorted_temp}")
print(f"28 appears:{count_28}")

def get_value(value):
  try :
    age=int(value)
    if age<0 or age>120:
        return f"Invalid age:{value}"
    return f"Valid age:{value}"
  except ValueError:
          return "Error please enter valid number"




print(get_value("25"))
print(get_value("abc"))
print(get_value("-5"))
print(get_value("150"))

value=23
a=int(value)
print(a)

students=[]
def add_student(name,mark):
  try:
    mark=int(mark)
    if mark < 0 or mark >100:
      return "Invalid mark"
    cleaned_name=name.strip().title()
    students.append({"name":cleaned_name,"mark":mark})
    return f"{cleaned_name} successfully added"
  except ValueError:
    return "give me the valid mark"

print(add_student("  ravi  ", "85"))
print(add_student("PRIYA", "92"))
print(add_student("karthik", "abc"))
print(add_student("sneha", "150"))

for s in students:
  print(f"{s["name"]}:{s["mark"]}")

contacts = {
    "Ravi": "9876543210",
    "Priya": "8765432109",
    "Karthik": "7654321098"
}

def search_contact(name):
    if name in contacts:
          return (f"{name}: {contacts[name]}")

    return (f"contact not found :{name}")

def add_contact(name, phone):
      if phone.isdigit():
        contacts[name]=phone
        print(f"{name} added sucessfully")
      else:
        print("Error: Invalid phone number")

print(search_contact("Ravi"))
print(search_contact("Sneha"))
add_contact("Meena", "6543210987")
add_contact("Kumar", "abc123")
print(search_contact("Meena"))