# -*- coding: utf-8 -*-
"""day 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iJuYMcB-Y9m_mPxC1mRhCpZ4rdj8fVaG
"""

import numpy as np
marks = np.array([45, 82, 31, 76, 55, 91, 48, 63, 88, 72])
zeros=np.zeros(5)
ones=np.ones(5)
Range=np.arange(1,10,2)
print(f"Marks:{marks}")
print(f"Zeros:{zeros}")
print(f"Ones:{ones}")
print(f"Range:{Range}")
print(f"Type:{type(marks)}")
print(f"Shape:{marks.shape}")
print(f"Dimensions:{marks.ndim}")

import numpy as np
marks = np.array([45, 82, 31, 76, 55, 91, 48, 63, 88, 72])

print(f"Mean :{np.mean(marks)}")
print(f"Median :{np.median(marks)}")
print(f"Std :{np.std(marks)}")
print(f"variance :{np.var(marks)}")
print(f"Min :{np.min(marks)}")
print(f"Max :{np.max(marks)}")

print(f"\nMarks+5 :{marks+5}")
print(f"Marks*2 :{marks}")
print(f"Passed :{marks [marks>=60]}")
print(f"Failed :{marks[marks<60]}")

import numpy as np
marks_2d=np.array([[85, 92, 78, 88],
    [71, 65, 80, 75],
    [90, 88, 95, 92]])

print(f"shape:{marks_2d.shape}")
print(f"all marks:{marks_2d}")
print(f"student 1:{marks_2d[0]}")
print(f"student 2:{marks_2d[1]}")
print(f"subject:{marks_2d[:,0]}")
print(f"over all average:{np.mean(marks_2d):.2f}")
print(f"Each student average:{np.mean(marks_2d, axis=1)}")
print(f"Each subject average:{np.mean(marks_2d, axis=0)}")

import numpy as np
prices = np.array([25, 45, 12, 78, 34, 56, 89, 23, 67, 41])
min_price=np.min(prices)
max_price=np.max(prices)
normalize=(prices-min_price)/(max_price-min_price)
mean=np.mean(prices)
std=np.std(prices)
standarized=(prices-mean)/std
print(f"original:{prices}")
print(f"min:{min_price}, max:{max_price}")
print(f"normalize:{normalize.round(2)}")
print(f"\nmean:{mean},std:{std}")
print(f"standarized:{standarized.round(2)}")

import numpy as np

scores = np.array([67, 89, 45, 92, 73, 56, 88, 71, 95, 62])
mean_scores=np.mean(scores)
median_scores=np.median(scores)
std_scores=np.std(scores)
print(f"Mean:{mean_scores}")
print(f"Median:{median_scores}")
print(f"Std:{std_scores}")

max_score=np.max(scores)
highest_index=np.argmax(scores)
print(f"Highest Scores:Index {highest_index},score {max}")

min_score=np.min(scores)
normalize=(scores-min_score)/(max_score-min_score)
print(f"Normalized:{normalize}")

average=np.mean(scores)
above_avg=scores[average<scores]
count=len(above_avg)
print(f"Above average:{count} Students")

grades = []
for score in scores:
    if score>=90:
      grades.append("A")
    elif score>=75:
      grades.append("B")
    elif score>=60:
      grades.append("C")
    else:
      grades.append("F")
    pass
print(f"Grades: {grades}")